### ISSUE TITLE
How to get static port assignment in HOST networking mode for docker-kafka-marathon

### ISSUE THREAD

**Issue by archmangler** [tobilg/docker-kafka-marathon#1]
When I use this image with marathon, the ports for kafka are allocated dynamically.
However when I try configure static ports using the recommended ports [x,y....] statement, or "portDefinitions" statement,  still get dynamically allocated ports.
But, I'd like to have the brokers accessible on port 9092 for other services which use the default kafka broker port, so dynamic ports are going to be very difficult to work with.

When I use the static port configuration for the marathon service definition, with static ports 19092, I get this error, which seems to indicate that the port numbers are being used as broker IDs:

`[2017-12-08 11:14:26,793] FATAL Fatal error during KafkaServerStartable startup. Prepare to shutdown (kafka.server.KafkaServerStartable)
java.lang.RuntimeException: A broker is already registered on the path /brokers/ids/19092. This probably indicates that you either have configured a brokerid that is already in use, or else you have shutdown this broker and restarted it faster than the zookeeper timeout so it appears to be re-registering.
	at kafka.utils.ZkUtils$.registerBrokerInZk(ZkUtils.scala:174)
	at kafka.server.KafkaHealthcheck.register(KafkaHealthcheck.scala:58)
	at kafka.server.KafkaHealthcheck.startup(KafkaHealthcheck.scala:45)
	at kafka.server.KafkaServer.startup(KafkaServer.scala:124)
	at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:29)
	at kafka.Kafka$.main(Kafka.scala:46)
	at kafka.Kafka.main(Kafka.scala)
[2017-12-08 11:14:26,795] INFO [Kafka Server 19092], shutting down (kafka.server.KafkaServer)
`

Is this an issue with the image confguration?

**Comment by tobilg** [comment]
This project is marked as deprecated and no longer maintained. Why don't you use https://universe.dcos.io/#/package/kafka/docs
